### ISSUE TITLE
Withdraw coordinates from any string

### ISSUE THREAD

**Issue by aleksey-kozakov** [markstos/parse-coordinates#1]
It would be great to be able to Withdraw from any string, like "Coordinates -80.21, 21.32" or "any string -80.21, 21.32 here"

**Comment by markstos** [comment]
I won't add this feature. If there's a junk around the string, it's not clear whether it's safe to discard or whether it perhaps it has meaning and it would be a silent failure to discard it.  If you want to extracts coordinates from a string, you could use a regex to remove all the characters which are not numbers, the comma, period or negative sign. Then you could call this module on the result.

Or you could fork this module and the feature to your fork.

**Comment by aleksey-kozakov** [comment]
Ok, thanks.

I thought  it would be a valuable feature inside the module.
